// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:fireauth/const/fire_api_keys.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: FireKeys.web,
    appId: '1:656317995107:web:32b01a87fcde73fd19c056',
    messagingSenderId: '656317995107',
    projectId: 'firebase-auth-second-bloc',
    authDomain: 'fir-auth-second-bloc.firebaseapp.com',
    storageBucket: 'firebase-auth-second-bloc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: FireKeys.android,
    appId: '1:656317995107:android:115e4ec90d8375a819c056',
    messagingSenderId: '656317995107',
    projectId: 'firebase-auth-second-bloc',
    storageBucket: 'firebase-auth-second-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: FireKeys.apple,
    appId: '1:656317995107:ios:f3e63956dea7b16219c056',
    messagingSenderId: '656317995107',
    projectId: 'firebase-auth-second-bloc',
    storageBucket: 'firebase-auth-second-bloc.appspot.com',
    iosClientId:
        '656317995107-utvt5fj6l7ui7pfqkq58pgvmog3d2jfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: FireKeys.apple,
    appId: '1:656317995107:ios:f3e63956dea7b16219c056',
    messagingSenderId: '656317995107',
    projectId: 'firebase-auth-second-bloc',
    storageBucket: 'firebase-auth-second-bloc.appspot.com',
    iosClientId:
        '656317995107-utvt5fj6l7ui7pfqkq58pgvmog3d2jfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireauth',
  );
}
